[project]
name = "ifcd0112-pytest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Carlos Chacón", email = "chaconmooncarlos@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pytest>=9.1.1",
]

[project.scripts]
ifcd0112-pytest = "ifcd0112_pytest:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
